name: Update gitlab mirror on commits

on:
  workflow_dispatch:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push
        run: |
          git remote add gast https://gitlab.gast.it.uc3m.es/schica/CVEScannerV2
          cat << EOF > /usr/local/bin/credential-helper
          #!/bin/bash
          cat /tmp/gitlab
          EOF
          chmod +x /usr/local/bin/credential-helper
          git config --global credential.helper /usr/local/bin/credential-helper
          cat << EOF > /tmp/gitlab
          username=oauth2
          password=${{ secrets.GITLAB_TOKEN }}
          EOF
          git push -f gast master
